# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20170219_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
